[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
dyn-clone = "1.0.17"
either = "1.13.0"
gloo = "0.11.0"
itertools = "0.13.0"
proconio = "0.5.0"
rand = { version = "0.8.5", features = ["small_rng"] }
yew = { version = "0.21.0", features = ["csr"] }
